In [1]:
import numpy as np

In [3]:
mydata1 = np.array([0,1,2])

In [5]:
mydata1

array([0, 1, 2])

In [7]:
print(mydata1)

[0 1 2]


In [9]:
mydata2 = np.array([[0,1],[2,3],[4,5]])

In [11]:
print(mydata2)

[[0 1]
 [2 3]
 [4 5]]


In [13]:
mydata3 = np.array([[[0,0,0,0],[1,1,1,1],[2,2,2,2]],[[3,3,3,3],[4,4,4,4],[5,5,5,5]]])

In [15]:
print(mydata3)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]
  [5 5 5 5]]]


In [3]:
import numpy as np

In [5]:
mydata_1 = np.arange(3,dtype = np.int32)

In [7]:
print(mydata_1)

[0 1 2]


In [9]:
mydata_2 = np.arange(3,9,3)

In [11]:
print(mydata_2)

[3 6]


In [13]:
mydata_3 = np.arange(3,10,3)

In [15]:
print(mydata_3)

[3 6 9]


In [17]:
import numpy as np 

In [19]:
my_data1 = np.eye(3)

In [21]:
print(my_data1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
my_data2 = np.eye(3,2)

In [29]:
print(my_data2)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [31]:
my_data3 = np.eye(3,5,k=1)

In [33]:
print(my_data3)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [35]:
my_data4 = np.eye(3)[[0,1,0,2]]

In [39]:
print(my_data4)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [41]:
#数组对象的属性

In [43]:
import numpy as np

In [45]:
my_data1 = np.arange(4).reshape((2,2))

In [47]:
print(my_data1)

[[0 1]
 [2 3]]


In [49]:
my_data2 = np.reshape(my_data1,(4,1))

In [51]:
print(my_data2)

[[0]
 [1]
 [2]
 [3]]


In [53]:
my_data3 = np.arange(4)

In [55]:
print(my_data3)

[0 1 2 3]


In [57]:
my_data4 = np.resize(my_data3,(3,2))

In [59]:
print(my_data4)

[[0 1]
 [2 3]
 [0 1]]


In [79]:
#数组元素的索引方法

In [1]:
import numpy as np

In [3]:
my_data1 = np.arange(8)

In [7]:
print(my_data1)

[0 1 2 3 4 5 6 7]


In [11]:
my_data2 = my_data1[np.array([2,-2])]

In [13]:
print(my_data2)

[2 6]


In [15]:
my_data3 = my_data1.reshape((4,2))

In [17]:
print(my_data3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [19]:
my_data4 = my_data3[2,1]

In [21]:
print(my_data4)

5


In [23]:
#张量的创建

In [25]:
#在神经网络中，常用张量（tensor）来统一表示所有的数值数据在PyTorch,TensorFlow等编程框架中均使用张量来作为数值数据的载体，其对应了神经网络中在各个节点之间传递流动的数据。

In [27]:
import torch

In [29]:
#直接创建张量

In [31]:
#使用requires_grad参数来表示该张量是否需要计算梯度

In [33]:
my_data1 = torch.tensor([0.0,1.0,2.0,3.0],requires_grad = True)

In [35]:
print(my_data1)

tensor([0., 1., 2., 3.], requires_grad=True)


In [37]:
my_data2 = torch.ones(3,2)

In [39]:
print(my_data2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [41]:
my_data3 = torch.zeros(3,2)

In [43]:
print(my_data3)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [45]:
my_data4 = torch.rand(3,2)

In [47]:
print(my_data4)

tensor([[0.6432, 0.1401],
        [0.3991, 0.0647],
        [0.9925, 0.3819]])


In [49]:
#从其他张量创建新张量

In [51]:
my_data5 = torch.rand_like(my_data1)

In [53]:
print(my_data5)

tensor([0.2666, 0.3068, 0.1633, 0.1167])


In [55]:
my_data6 = torch.zeros_like(my_data1)

In [57]:
print(my_data6)

tensor([0., 0., 0., 0.])


In [59]:
my_data7 = torch.ones_like(my_data1)

In [61]:
print(my_data7)

tensor([1., 1., 1., 1.])


In [63]:
#张量与NUMPY数组转换方法

In [1]:
import torch

In [5]:
import numpy as np

In [7]:
my_data1 = np.array([0,1,2,3])

In [9]:
print(my_data1)

[0 1 2 3]


In [11]:
my_data2 = torch.from_numpy(my_data1)

In [13]:
print(my_data2)

tensor([0, 1, 2, 3], dtype=torch.int32)


In [15]:
my_data3 = torch.zeros(2,2)

In [17]:
my_data4 = my_data3.numpy()

In [19]:
print(my_data3)

tensor([[0., 0.],
        [0., 0.]])


In [21]:
print(my_data4)

[[0. 0.]
 [0. 0.]]


In [23]:
#张量的常用属性

In [25]:
#在GPU上创建张量的不同方式

In [27]:
#my_data1 = torch.tensor([0,1,2,3],device = torch.device('cuda:1'))

In [31]:
#my_data2 = torch.tensor([0,1,2,3],device = torch.device('cuda',1))

In [33]:
#my_data3 = torch.tensor([0,1,2,3],device = 'cuda',1)

In [35]:
#在CPU上创建张量

In [37]:
my_device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [41]:
my_data4 = torch.tensor([0,1,2,3],device = my_device)

In [43]:
print(my_data4)

tensor([0, 1, 2, 3])


In [45]:
#张量属性的转换

In [47]:
import torch

In [49]:
#张量设备类型转换

In [51]:
my_data1 = torch.tensor([0,1,2,3])

In [55]:
#my_data1 = my_data1.to('cuda')

In [57]:
#张量数据类型转换

In [69]:
my_data2 = my_data1.to(torch.int8)

In [65]:
print(my_data1)

tensor([0., 1., 2., 3.], dtype=torch.float64)


In [71]:
print(my_data2)

tensor([0, 1, 2, 3], dtype=torch.int8)


In [73]:
#张量形状属性转换

In [75]:
import torch

In [77]:
my_data1 = torch.tensor([0,1,2,3])

In [79]:
my_data2 = my_data1.reshape(2,2)

In [81]:
print(my_data2)

tensor([[0, 1],
        [2, 3]])


In [83]:
my_data3 = torch.arange(6)

In [89]:
my_data4 = my_data3.reshape(3,2)

In [91]:
print(my_data4)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [93]:
#对张量的常用操作

In [1]:
import torch

In [5]:
a = torch.randn(8192,8192,dtype = torch.float)

In [7]:
b = torch.randn(8192,8192,dtype = torch.float)

In [9]:
#在CPU上计算

In [11]:
c = torch.matmul(a,b)

In [13]:
#在深度学习处理器（DLP）上计算

In [15]:
#device = torch.device('dlp')

In [17]:
#a_dlp = a.to(device)

In [19]:
#b_dlp = b.to(device)

In [21]:
#c_dlp = torch.matmul(a_dlp,b_dlp)